version: '3.9'

volumes:
  postgres:
  redis:
  pgadmin-data:


services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      TZ: ${TZ}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  app:
    container_name: application_backend
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: postgres
    volumes:
      - .:/usr/src/app

