version: '3.9'

volumes:
  postgres:
  redis:


services:
  database:
    image: postgres:14
    ports:
      - '3334:5432'
    env_file:
      - ./.env
    environment:
      TZ: ${TZ}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  app:
    container_name: application_backend
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run start
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
    x-develop:
      watch:
        - action: rebuild
          path: .

