export enum AuthErrorEnum {
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  REFRESH_TOKEN_NOT_FOUND = 'REFRESH_TOKEN_NOT_FOUND',
  REFRESH_TOKEN_FAILED = 'REFRESH_TOKEN_FAILED',
  INVALID_CODE_VERIFICATION = 'INVALID_CODE_VERIFICATION',
}
